server:
  port: 8086

spring:
  application:
    name: processing-service

app:
  ai-service:
    url: ${AI_SERVICE_URL:http://localhost:8082}
  metadata-service:
    url: ${METADATA_SERVICE_URL:http://localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.smartdrive.processingservice: INFO
    org.springframework.cloud.aws: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
